### ISSUE TITLE
npm启动报错

### ISSUE THREAD

**Issue by zhangyuanliang** [EthanOrange/wechat-redirect#14]
npm启动报错，希望提交成功版本
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/11.13.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.7.0
3 info using node@v11.13.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle wechat-redirect@1.0.0~prestart: wechat-redirect@1.0.0
6 info lifecycle wechat-redirect@1.0.0~start: wechat-redirect@1.0.0
7 verbose lifecycle wechat-redirect@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle wechat-redirect@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/zl/GitHub/wechat-redirect/node_modules/.bin:.:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:.:/Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home//bin:/Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home//bin
9 verbose lifecycle wechat-redirect@1.0.0~start: CWD: /Users/zl/GitHub/wechat-redirect
10 silly lifecycle wechat-redirect@1.0.0~start: Args: [ '-c', 'cross-env PORT=3005 node index.js' ]
11 silly lifecycle wechat-redirect@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle wechat-redirect@1.0.0~start: Failed to exec start script
13 verbose stack Error: wechat-redirect@1.0.0 start: `cross-env PORT=3005 node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:193:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:193:13)
13 verbose stack     at maybeClose (internal/child_process.js:1001:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
14 verbose pkgid wechat-redirect@1.0.0
15 verbose cwd /Users/zl/GitHub/wechat-redirect
16 verbose Darwin 18.0.0
17 verbose argv "/usr/local/Cellar/node/11.13.0/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v11.13.0
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 1
22 error wechat-redirect@1.0.0 start: `cross-env PORT=3005 node index.js`
22 error Exit status 1
23 error Failed at the wechat-redirect@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by AlwDnal** [comment]
一样的错 没有解决了
